### ISSUE TITLE
Unable to use print via service with stored credentials

### ISSUE THREAD

**Issue by hundekoerper** [lassediercks/Mutualistic#1]
**How to reproduce:**
Visit the site and enter you credentials. Things get saved to local storage. Visit the site again and see that values from storage are applied to the preview. If you click `print via service` nothing will happen (no request will be fired).

**Expected behavior:**
It will print a PDF with the stored values.

![jun-29-2018 11-37-45](https://user-images.githubusercontent.com/12618489/42085514-ecd06442-7b90-11e8-9145-41c2124b6af1.gif)

**Comment by lassediercks** [comment]
We went to the coding cave with our best engineers and consultants and were able to fix this issue right away for you
